### ISSUE TITLE
anchor(<a>...</a>) in the section before another section cannot be clicked when using layout

### ISSUE THREAD

**Issue by mikelue** [andriusvelykis/reflow-maven-skin#45]
## Problem
1. The `<a>..</a>` cannot be clicked when using layout.
2. Even for the section, it cannot be drag-and-select.
## My Environment
1. Java 8
2. Maven 3.3.3
3. maven-site-plugin 3.4.1-SNAPSHOT
## Example

`sandbox.md`
1. The link in "Chapter 1" cannot be clicked
2. The link in "Chapter 2" is fine

``` markdown
## Chapter 1

[Google](https://www.google.com)

---

## Chapter 2

[Google](https://www.google.com)
```

`site.xml`

``` xml
<project
    xmlns="http://maven.apache.org/DECORATION/1.6.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://maven.apache.org/DECORATION/1.6.0 http://maven.apache.org/xsd/decoration-1.6.0.xsd"
>

<custom>
    <reflowSkin>
        <pages>
            <sandbox>
                <sections>
                    <columns>2</columns>
                    <columns>2</columns>
                </sections>
            </sandbox>
        </pages>
    </reflowSkin>
</custom>

</project>

```
## Diagnosis

In the file [reflow-skin.css](https://github.com/andriusvelykis/reflow-maven-skin/blob/master/reflow-maven-skin/src/main/resources/css/reflow-skin.css), if I remove the `content:"";` property:

``` css
h1[id]:before,
h2[id]:before,
h3[id]:before,
h4[id]:before,
h5[id]:before,
h6[id]:before,
a[name]:before {
    display:block; 
    /* content:""; */
    height:90px; 
    margin:-90px 0 0; 
}
```

**The problem would be solved**.  
**But I have no idea if this is a sensible solution**.
